// src/generator/markdown.rs - Markdown 文档生成器

use crate::error::Result;
use crate::generator::DocumentGenerator;
use crate::schema::DatabaseSchema;
use chrono::Utc;

/// Markdown 文档生成器
pub struct MarkdownGenerator;

impl MarkdownGenerator {
    /// 创建新的 Markdown 生成器
    pub fn new() -> Self {
        Self
    }
}

impl Default for MarkdownGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl DocumentGenerator for MarkdownGenerator {
    fn generate(&self, schema: &DatabaseSchema) -> Result<String> {
        let mut md = String::new();

        // 标题
        md.push_str(&format!("# {} - Database Schema\n\n", schema.database));
        md.push_str(&format!("> Generated by crab-shell v0.1.0 on {}\n\n", Utc::now().format("%Y-%m-%d %H:%M:%S")));

        // 目录
        md.push_str("## Table of Contents\n\n");
        for table in &schema.tables {
            md.push_str(&format!("- [{}](#{}) ({} columns", table.name, table.name, table.column_count()));
            if table.index_count() > 0 {
                md.push_str(&format!(", {} indexes", table.index_count()));
            }
            md.push_str(")\n");
        }
        md.push_str("\n---\n\n");

        // 每个表的详细信息
        for table in &schema.tables {
            md.push_str(&format!("## {}\n\n", table.name));
            if let Some(comment) = &table.comment {
                md.push_str(&format!("> {}\n\n", comment));
            }

            // 列信息表格
            md.push_str("| # | Column | Type | Nullable | Default | Comment |\n");
            md.push_str("|---|--------|------|----------|---------|---------|\n");
            for (i, col) in table.columns.iter().enumerate() {
                let nullable = if col.nullable { "YES" } else { "NO" };
                let default = col.default_value.as_deref().unwrap_or("-");
                let comment = col.comment.as_deref().unwrap_or("-");
                md.push_str(&format!("| {} | {} | {} | {} | {} | {} |\n",
                    i + 1, col.name, col.data_type, nullable, default, comment));
            }
            md.push('\n');

            // 主键信息
            if let Some(pk) = &table.primary_key {
                md.push_str(&format!("**Primary Key**: `{}` (`{}`)\n\n", pk.columns.join(", "), pk.name));
            }

            // 外键信息
            if !table.foreign_keys.is_empty() {
                md.push_str("**Foreign Keys**:\n\n");
                md.push_str("| Name | Column(s) | References |\n");
                md.push_str("|------|-----------|------------|\n");
                for fk in &table.foreign_keys {
                    md.push_str(&format!("| {} | {} | {}({}) |\n",
                        fk.name, fk.columns.join(", "), fk.referenced_table, fk.referenced_columns.join(", ")));
                }
                md.push('\n');
            }

            // 索引信息
            if !table.indexes.is_empty() {
                md.push_str("**Indexes**:\n\n");
                md.push_str("| Name | Columns | Unique | Type |\n");
                md.push_str("|------|---------|--------|------|\n");
                for idx in &table.indexes {
                    let unique = if idx.is_unique { "YES" } else { "NO" };
                    let idx_type = idx.index_type.as_deref().unwrap_or("btree");
                    md.push_str(&format!("| {} | {} | {} | {} |\n",
                        idx.name, idx.columns.join(", "), unique, idx_type));
                }
                md.push('\n');
            }

            md.push_str("---\n\n");
        }

        Ok(md)
    }

    fn file_extension(&self) -> &str {
        "md"
    }

    fn name(&self) -> &str {
        "Markdown"
    }
}
